kind: PersistentVolume
apiVersion: v1
metadata:
  name: artifactory
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/artifactory/"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: artifactory
    tier: artifactory
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifactory
  labels:
    app: artifactory
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: artifactory
        tier: artifactory
    spec:
      containers:
      - image: danillosl/docker-artifactory:latest
        name: artifactory
        securityContext:
          privileged: true
        ports:
        - containerPort: 8081
          name: artifactory
        volumeMounts:
        - name: artifactory-persistent-storage
          mountPath: /root/.artifactory
        - name: docker
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker
        hostPath:
          path: /var/run/docker.sock
      - name: artifactory-persistent-storage
        persistentVolumeClaim:
          claimName: artifactory-claim
